In [1]:
import ydata_profiling as yp

/Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
/Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages/visions/backends/shared/nan_handling.py:51: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def hasna(x: np.ndarray) -> bool:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow

In [2]:
table = pd.read_csv('../data/raw/Variables_IMSS.csv')

In [3]:
table['inference_date'] = table['inference_date'].astype('datetime64[ns]') 
table['target'] = table.target.astype("category")
table=table.drop(['Unnamed: 0'],axis=1)
table=table.drop(['curp'],axis=1)
table=table.drop(['Job_Maturity_Year'],axis=1)
table=table.drop(['Job_Maturity_Month'],axis=1)
table=table.drop(['Job_Maturity_Day'],axis=1)

from datetime import datetime
today = datetime.today()
target_date = pd.to_datetime(table['inference_date'])
days_past = (today - target_date).dt.total_seconds() / (60 * 60 * 24)
table['inference_date'] =  days_past

target_date = pd.to_datetime(table['last_job_end_date'])
days_past = (today - target_date).dt.total_seconds() / (60 * 60 * 24)
table['last_job_end_date'] =   days_past

table['ratio_Employer_yearMat'] = table['ratio_Employer_yearMat'].replace(np.inf, np.nan)
table['ratio_Employer_monMat'] = table['ratio_Employer_monMat'].replace(np.inf, np.nan)

table.drop_duplicates(inplace=True)

table.describe()

,inference_date,Job_Maturity_Week,Status_on_InferenceD,No_Job_history,Max_space_between_jobs,Mean_space_between_jobs,count_job_gap,last_job_end_date,last_job_base_salary,count_distinct_FederalEntity,Federal_entity_binary,Ratio_FedEnt_DistEmploy,ratio_Employer_yearMat,ratio_Employer_monMat,distinct_employer_registy,comp_entidades_curp,ratio_weeksmatured_18reportdate,ratio_weekscontributed_18reportdate,ratio_weekswithdrawn_18reportdate
count,83441.000000,82926.000000,83441.000000,83441.000000,80961.000000,80961.000000,82926.000000,82926.000000,82926.000000,82926.000000,83441.000000,82926.000000,82754.000000,81782.000000,82926.000000,82926.000000,82926.000000,82926.000000,82926.000000
mean,391.653924,336.839158,0.469266,0.006172,726.059930,175.672730,5.813955,1448.306414,318.303028,2.056146,0.570055,0.449908,2.975227,0.195527,7.223959,0.573475,0.330912,0.315774,0.026813
std,84.692883,321.267066,0.516639,0.078320,1117.372885,334.611237,15.222311,1927.803927,318.021110,1.289753,0.495071,0.295547,7.481346,0.267411,6.754753,0.494575,0.285686,0.278875,0.050841
min,267.616401,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,203.616401,0.000000,1.000000,0.000000,0.030000,0.030000,0.000000,1.000000,0.000000,-1.186306,-0.771020,-0.252430
25%,313.616401,84.000000,0.000000,0.000000,3.000000,1.000000,1.000000,355.616401,149.590000,1.000000,0.000000,0.220000,0.730000,0.060000,3.000000,0.000000,0.098280,0.089669,0.000000
50%,386.616401,246.000000,0.000000,0.000000,297.000000,61.704545,3.000000,516.616401,209.040000,2.000000,1.000000,0.330000,1.390000,0.110000,5.000000,1.000000,0.303376,0.280000,0.000000
75%,455.616401,496.000000,1.000000,0.000000,952.000000,197.750000,7.000000,1705.616401,361.370000,3.000000,1.000000,0.570000,2.740000,0.220000,10.000000,1.000000,0.543701,0.519552,0.046005
max,589.616401,3292.000000,3.000000,1.000000,15330.000000,6524.000000,1242.000000,15839.616401,2405.500000,19.000000,1.000000,1.000000,300.000000,5.500000,118.000000,1.000000,2.238095,2.595238,0.751656

In [13]:
! pip install ipywidgets

ProfileReport = yp.ProfileReport(table, title="IMSS", explorative=True)
ProfileReport

Requirement already satisfied: ipywidgets in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (8.0.6)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipywidgets) (6.23.1)
Requirement already satisfied: ipython>=6.1.0 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipywidgets) (8.12.2)
Requirement already satisfied: traitlets>=4.3.1 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipywidgets) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.7 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipywidgets) (4.0.7)
Requirement already satisfied: jupyterlab-widgets~=3.0.7 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipywidgets) (3.0.7)
Requirement already satisfied: appnope in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (0.1.3)
Requirement already satisfied: comm>=0.1.1 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (0.1.3)
Requirement already satisfied: debugpy>=1.6.5 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (8.2.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (5.3.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (0.1.6)
Requirement already satisfied: nest-asyncio in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (1.5.6)
Requirement already satisfied: packaging in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (23.1)
Requirement already satisfied: psutil in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (5.9.5)
Requirement already satisfied: pyzmq>=20 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (25.0.2)
Requirement already satisfied: tornado>=6.1 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets) (6.3.2)
Requirement already satisfied: backcall in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: decorator in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.18.2)
Requirement already satisfied: pickleshare in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.38)
Requirement already satisfied: pygments>=2.4.0 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.2)
Requirement already satisfied: typing-extensions in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (4.5.0)
Requirement already satisfied: pexpect>4.3 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: importlib-metadata>=4.8.3 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets) (6.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.5.1->ipywidgets) (3.5.1)
Requirement already satisfied: ptyprocess>=0.5 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets) (0.2.6)
Requirement already satisfied: executing>=1.2.0 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: pure-eval in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Requirement already satisfied: zipp>=0.5 in /Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets) (3.15.0)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:

from pycaret.classification import *

In [5]:
table_exp = table.sample(frac=0.20, random_state=123)
table_unseen=table.drop(table_exp.index)
table_exp.shape,table_unseen.shape

((16688, 20), (66753, 20))

In [8]:
from pycaret.utils import set_experiment

# Set the experiment and specify the local file path
set_experiment('exp3', log_experiment=True, experiment_name_file='../mlruns')

ImportError: cannot import name 'set_experiment' from 'pycaret.utils' (/Users/agpascoemacmini3/miniconda3/envs/project-template2/lib/python3.8/site-packages/pycaret/utils/__init__.py)

In [6]:
dataset = setup( data = table_exp, target = 'target', session_id=123,
                 remove_outliers=True, outliers_threshold=0.05,
                 transformation=True, 
                 remove_multicollinearity=True,
                 log_experiment=True, experiment_name='exp4',
                 log_plots = True, 
                 fix_imbalance=True,
                 normalize=True, normalize_method='zscore')

In [7]:
best= compare_models(sort='Recall')

In [ ]:
lr_model = create_model("lr")

In [ ]:
plot_model(lr_model, plot='pr')

In [ ]:
plot_model(lr_model, plot='confusion_matrix')